name: music_player_by_ercan
description: An offline music player app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  flutter_audio_query: ^0.3.5+6
  on_audio_query: ^2.6.1
  permission_handler: ^8.2.6
  audioplayers: ^0.20.1
  shared_preferences: ^2.0.15
  auto_size_text: ^3.0.0
  json_serializable: ^6.3.1
  flutter_slidable: ^2.0.0
  audio_manager: ^0.8.2
#  android_intent_plus: ^3.0.2

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/neon_headset.jpg
    - assets/icon.png
    - assets/image.png
    - assets/music.png
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/Manrope-Light.ttf